version: '3'

networks:
  backend:
    driver: "bridge"

services:
  pgsql:
    build: ${DB_PATH}/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - '54321:5432'
    volumes:
      - ${DB_PATH}/postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
  redis:
    build: ${CACHE_PATH}/redis
    ports:
      - '63790:6379'
    volumes:
      # - ${CACHE_PATH}/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      # Redis startup command tells redis data to persist its data in the /data directory in the container
      - ${CACHE_PATH}/data:/data
    restart: always
    privileged: true
    networks:
      - backend
