version: '3'

networks:
  backend:
    driver: "bridge"

services:
  pgsql:
    build: ./postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - '54321:5432'
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    networks: 
      - backend
  redis:
    build: ./redis
    ports:
      - '63790:6379'
    # volumes: 
      # - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    privileged: true
    networks: 
      - backend
