version: '3'

services:
  postgres:
    build: ./postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - '54321:5432'
    volumes: 
      ./data:/var/lib/postgresql/data
    restart: always